events { 
    worker_connections 1024; 
}

http {
    # Aquí le decimos a Nginx quiénes son los trabajadores
    upstream backend_api {
        # 'app' es el nombre del servicio en el docker-compose.
        # Docker DNS automáticamente enviará el tráfico a las 3 réplicas.
        server app:3000; 
    }

    server {
        listen 80;

        location / {
            # Nginx recibe la petición y la avienta al grupo 'backend_api'
            proxy_pass http://backend_api;
            
            # Pasamos las IPs reales para que Node sepa quién hizo la petición
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}